# Site settings

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vibbycom.github.io" # the base hostname & protocol for your site

canonical: "https://www.vibby.com"

# Build settings
markdown: kramdown


include: ["_pages"]
