# Site settings

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vibby.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


include: ["_pages"]

stylus:
  compress: true
  path: ./_stylus
